-
  branches:
    only:
      - master
  configuration: [Release]
  os: Visual Studio 2017
  version: 1.0.0-{branch}-{build}
  install:
    - cmd: cd src\Spendix.Web
    - cmd: cd ..\..
    - cmd: node --version
    - ps: dotnet --info
  before_build:
    - cmd: dotnet restore .\Spendix.sln
  build:
    project: Spendix.sln
    publish_wap: true
    verbosity: minimal
  # scripts to run after tests
  after_test:
    - cmd: dotnet publish src\Spendix.Web\ -o ..\..\SpendixWebDeploy --configuration Release
  artifacts:
    - path: SpendixWebDeploy
      name: SpendixWebDeploy
      type: WebDeployPackage

  #---------------------------------#
  #     deployment configuration    #
  #---------------------------------#

  # providers: Local, FTP, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment
  # provider names are case-sensitive!
  deploy:
    # Web Deploy deployment provider settings
    - provider: WebDeploy
      server:  https://spendix.scm.azurewebsites.net:443/msdeploy.axd?site=spendix
      website: spendix
      username: $spendix
      password:
        secure: UpBbc6DP0uwnq6iXoo5jrFdSKFPEQnNFy55aEy/X/ofgPjat1aA9OXuHbM4dIu9764izDvmkyuIxeHtJgD/2UA==
      ntlm: false
      remove_files: false
      app_offline: true
      do_not_use_checksum: true           # do not use check sum for comparing source and destination files. By default checksums are used.
      aspnet_core: true                   # artifact zip contains ASP.NET Core application
      aspnet_core_force_restart: true
    # Deploy to GitHub Releases
    - provider: GitHub
      release: v$(appveyor_build_version)
      auth_token:
        secure: R8frI8mgxikrHkqB4EY0i8k6wW2Ud14+BD80gMvez+7gaMKxnAkl0OZDkq5Zfn3E
      artifact: SpendixWebDeploy.zip           # upload all NuGet packages to release assets
      draft: false
      prerelease: false
      on:
        branch: master                # release from master branch only
        appveyor_repo_tag: false       # deploy on tag push only
-
  configuration: Debug
  os: Visual Studio 2017
  version: 1.0.0.{build}
  shallow_clone: true
  install:
    - cmd: cd src\Spendix.Web
    - cmd: cd ..\..
    - ps: dotnet --info
  before_build:
    - cmd: dotnet restore .\Spendix.sln
  build:
    project: Spendix.sln
    publish_wap: false
    verbosity: minimal
